language: java
install:
  gradle assemble
services:
  - docker
script:
  - gradle check
  - gradle docker
  - if [[ $TRAVIS_BRANCH == master && $TRAVIS_PULL_REQUEST == false ]]; then
      echo "$DOCKER_IO_PASSWORD" | docker login docker.io -u itasgmbhde --password-stdin;
      gradle dockerPush;
    fi