language: java
install:
  gradle assemble
services:
  - docker
script:
  - gradle check
  - gradle docker
  - echo "$DOCKER_IO_PASSWORD" | docker login docker.io -u itasgmbhde --password-stdin
  - gradle dockerPush